version: "3.3"

services:
  app:
    container_name: listing_frontend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    # ports:
    #   - "4050:4050"
    networks:
      - nginx-proxy-net

networks:
  nginx-proxy-net:
    external: true
